### ISSUE TITLE
Process sometimes left running after exit

### ISSUE THREAD

**Issue by daltskin** [stuartleeks/pick-a-browser#25]
When running pick-a-browser.exe from command line with a invalid url or missing url the app is sometimes left running.

## Steps

- Run `pick-a-browser.exe`
- The Following window will be displayed
![image](https://user-images.githubusercontent.com/1678318/149996406-2ac42747-ca9a-45d4-b0a7-6915a86c5083.png)
- Close the window or message box
- Open a PowerShell session and check for running instances `Get-Process -Name pick-a-browser`

**Comment by stuartleeks** [comment]
I've re-written tis in go, so I'm going to close. If this re-occurs then please re-open :-)
